[features]
seeds = false
skip-lint = false
[programs.localnet]
solplay_escrow = "GKvoVVd3eae8kaAe12P2hYQUPBphoE5mUEwP5ueJLqEa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/homegrownentllc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
